"""Đồng bộ schema bệnh nền chuẩn hóa trên PostgreSQL theo cách idempotent.

Migration này lưu lại trong source control phần schema hiện đã có trên Neon:
``diseases``, ``patient_conditions`` và ``disease_interactions.disease_id``.
Script không xóa dữ liệu và chỉ backfill các dòng tương tác chưa có ``disease_id``.

Chạy từ thư mục gốc dự án:
    python scripts/migrate_patient_conditions.py
"""

from sqlalchemy import text

from src.db.session import engine

POSTGRES_MIGRATION_SQL = """
CREATE TABLE IF NOT EXISTS diseases (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ten_benh VARCHAR(255) NOT NULL UNIQUE,
    ten_benh_vi VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS patient_conditions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_profile_id VARCHAR NOT NULL REFERENCES patient_profiles(id),
    disease_id INTEGER NOT NULL REFERENCES diseases(id),
    CONSTRAINT uq_patient_disease UNIQUE (patient_profile_id, disease_id)
);

ALTER TABLE disease_interactions
    ADD COLUMN IF NOT EXISTS disease_id INTEGER;

INSERT INTO diseases (ten_benh, ten_benh_vi)
SELECT
    min(ten_benh),
    max(ten_benh_vi)
FROM disease_interactions
WHERE ten_benh IS NOT NULL AND trim(ten_benh) <> ''
GROUP BY lower(trim(ten_benh))
ON CONFLICT (ten_benh) DO UPDATE
SET ten_benh_vi = COALESCE(diseases.ten_benh_vi, EXCLUDED.ten_benh_vi);

UPDATE disease_interactions AS interaction
SET disease_id = disease.id
FROM diseases AS disease
WHERE interaction.disease_id IS NULL
  AND lower(trim(interaction.ten_benh)) = lower(trim(disease.ten_benh));

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'disease_interactions_disease_id_fkey'
          AND conrelid = 'disease_interactions'::regclass
    ) THEN
        ALTER TABLE disease_interactions
            ADD CONSTRAINT disease_interactions_disease_id_fkey
            FOREIGN KEY (disease_id) REFERENCES diseases(id);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_disease_interactions_disease_id
    ON disease_interactions (disease_id);

CREATE INDEX IF NOT EXISTS idx_disease_interactions_medication_disease
    ON disease_interactions (medication_id, disease_id);
"""


def migrate() -> None:
    if engine.dialect.name != "postgresql":
        raise RuntimeError("Migration patient_conditions chỉ hỗ trợ PostgreSQL")

    with engine.begin() as connection:
        connection.execute(text(POSTGRES_MIGRATION_SQL))

    print("Đã đồng bộ schema diseases/patient_conditions/disease_interactions.disease_id")


if __name__ == "__main__":
    migrate()
